version: '3'

services:
  db-service:
    image: mysql:latest
    restart: unless-stopped
    container_name: db-service
    ports: 
      - ${MYSQL_PORT}:3306
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
  