version: '3'

services:
  consumer-service:
    build: 
      context: .
      dockerfile: Dockerfile.consumer
    restart: unless-stopped
    container_name: consumer-service-rs
    network_mode: host
    env_file:
      - .env
   