version: '3'

services:
  proxy-service:
    image: nginx:latest
    restart: unless-stopped
    container_name: proxy-service
    network_mode: host
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/templates:/etc/nginx/templates:ro
      - ./nginx/logs:/etc/nginx/logs
      - ./frontend:/var/www/frontend:ro
    env_file:
      - .env
